### ISSUE TITLE
Delete file on SD card not possible

### ISSUE THREAD

**Issue by freakezoid1604** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#1]
The delete in the filelist did not work.

Big thanks for your work.

**Comment by xreef** [comment]
Hi freakezoid1604,
we noticed that problem already, if you try to upload via web interface it works with other copy types it doesn't work.
I think can be an encoding problem.
Can you do some test please?
Thanks Renzo

**Comment by freakezoid1604** [comment]
I upload some files over the web interface and it did not work

overwriting also doesn't work

**Comment by xreef** [comment]
Please, try to format the SD and retry.
What is your system language?
Bye Renzo

**Comment by freakezoid1604** [comment]
My System is German Win 10 pro V 21H1 Build 19043.1348

I will try again and i have the same situation. 

additional i test it with
Microsoft Edge Version 96.0.1054.43 (Offizielles Build) (64-Bit)

**Comment by xreef** [comment]
I'll reopen on new similar issue.
Bye Renzo
