### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by saloid** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#11]
Hi. I tried to update to your firmware from release using web page (previosly there was original firmware). I uploaded webView file first and it was succesfull, but when I tried to upload main firmware I got "File error". And now I can't update both - getting same error. Also I can't downgrade to [original firmware](https://github.com/xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface/raw/master/firmware_release/MksWifi_WebView.bin)
![image](https://user-images.githubusercontent.com/22222390/148999724-88220b2f-48cf-4210-98e7-c7ca6cd00333.png)
![image](https://user-images.githubusercontent.com/22222390/148999409-94fc4fde-ad6d-44d9-bba6-33b6f529823a.png)

I'm using MKS Robin nano 1.4 PCB with original wifi module

**Comment by saloid** [comment]
I still can control my printer in "MKS cloud" app

**Comment by xreef** [comment]
Hi Saloid,
for now, download previous version and put It in the sd, then restart It.
I check if there is a problem on current version.
Bye Renzo

**Comment by saloid** [comment]
@xreef I put both files on SD card and succesfully updated. Thanks for your support). But previosly I tried to upload original file in the web page and it didn't work too.

**Comment by xreef** [comment]
Sometime if wifi isn't strength enough there can be transfer problem and artifact.
Next time, try to stay close to the wifi router with the printer.
Bye Renzo
