### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by WonderCRM** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#12]
Is it possible to add a telegram bot for printer control and status notifications?
Lib: https://github.com/cotestatnt/asynctelegram2

**Comment by xreef** [comment]
Hi WonderCMR,
It's a good idea.
Probably first I add the possibility to send email with photo of the printed part from the esp32 cam controlled by BeePrint.
But I add this feature in roadmap.
Bye Renzo
