### ISSUE TITLE
Add time estimated end printing

### ISSUE THREAD

**Issue by Anisan** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#15]
Time_estimate = ( time_elapsed / procent ) * (100 - procent)

**Comment by Anisan** [comment]
Time_estimate = ( time_elapsed / procent ) * (100 - procent)

**Comment by xreef** [comment]
Hi @Anisan,
It's a good idea, but the percentage that come from board doesn't has decimal, so I think it's not so realistic.
I release also the web interface if you want try to manage It.
Bye Renzo
