### ISSUE TITLE
Mks Robin Pro v1. 0

### ISSUE THREAD

**Issue by Moz72** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#16]
Mks Robin Pro. Web ui starts but no temp nothing is showing or updating.

**Comment by xreef** [comment]
Can you send me a link of the board and the firmware you had installed?
Bye Renzo

**Comment by Moz72** [comment]
Ich habe es hin bekommen, aber frag mich nicht wie🙈MeinDrucker ist ein Jgmaker Artist-d Pro. Der ein Mks robin pro v1.0 verbaut hat. Installiert habe ich aber ein firmware vom mks nano35 board plus die wifi.bin und dann ging alles.
Super Arbeit von dir👍👍👍👍👍

**Comment by xreef** [comment]
Hehehhehe... good!
Bye Renzo

**Comment by Moz72** [comment]
Es hat leider doch nicht geklappt😢
Habe dir eine Mail geschickt, ist die angekommen?
Gruß Marcus

**Comment by xreef** [comment]
Hi @Moz72,
I don't have the board so I can't do debug or other.
Sorry Renzo
