### ISSUE TITLE
webhook log

### ISSUE THREAD

**Issue by DavideWasTaken** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#17]
it would be awesome if you can receive webhook messages on discord or slack at the end of the work!

**Comment by xreef** [comment]
Hi @DavideWasTaken,
probably when I find some time, I'll develop an extension that uses the esp32-cam to send EMail with a photo (or telegram or other messaging).
But on MKS WiFi, the resource is very poor, and to do something similar, and I must rewrite a lot of code.

If you want to add the features request on the forum
https://www.mischianti.org/forums/forum/mischiantis-projects/mks-wifi-firmware-and-beeprint-web-interface/

Bye Renzo

**Comment by DavideWasTaken** [comment]
ok, thank you!
