### ISSUE TITLE
Uploading Files

### ISSUE THREAD

**Issue by rwoldberg** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#18]
I am having upload issues.  Most of the time the file upload does not complete.  I put some debug statments in the wifi-module, and it appears that it never reveived the lastFragment flag.  I think this is an issue in wifi firmware, however I am unable to compile it as the esp8266 core can not be downloaded from github as it appears there is a virus in one of the files.

**Comment by xreef** [comment]
Hi rwoldberg,
try to put your printer near to the router, probably the RSSI is not good.
Probably is the web part, some antivirus consider JS file malicious.
Bye Renzo

**Comment by rwoldberg** [comment]
When cloning https://github.com/makerbase-mks/Esp8266-Core-For-Arduino to try and build the wifi firmware, windows states that esptool.exe contains a virus.  Windows is reporting it as containing the Win32/Sality.AT virus.

I found the version of the board and libraires you are using so it apperars that I do not need to use the above version of the 8266 core to compile your version of the mkswifi, so the abocve is a non issue.

As for the uploading files, the file actually gets written completely, but it almost always is reported as a failure.  If I compare the file after it as been uploaded it is identical.  Although sometimes there is extra garbage at the end of the uploaded file.  I put debug statements in wifi_module.cpp in the marlin firmware and it appears that it never receives a packet marked as the last fragment.  I think this is the issue.

**Comment by xreef** [comment]
Hi,
I don't use that core, I use a standard one for my project.

I can't replicate the problem.

Bye renzo
