### ISSUE TITLE
web page 

### ISSUE THREAD

**Issue by IotSHCJC** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#27]
Hello 
     I downloaded your code and it worked, I want to modify the page, but I don't know the development process of this page modification, it seems to use javascript and webpacket to modify, can you tell me the page modification process?

**Comment by xreef** [comment]
Hi @IotSHCJC,
you can find the React redux project in this repository.
https://github.com/xreef/beeprint_3d_printer_web_interface

you can follow the steps in the README.

Bye Renzo
