### ISSUE TITLE
Portuguese translate

### ISSUE THREAD

**Issue by RonaldoRisso** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#28]
hi, i added the portuguese translation in the file
I couldn't compile here

https://drive.google.com/drive/folders/1slwaNuX-UHMA1ACqXRykcxYB_toKId8X

**Comment by RonaldoRisso** [comment]
corrected and reuploaded data.json

**Comment by xreef** [comment]
added

**Comment by xreef** [comment]
Give me feedback on the lastest version with your translation.
Thanks Renzo

**Comment by RonaldoRisso** [comment]
> Give me feedback on the lastest version with your translation. Thanks Renzo



https://drive.google.com/file/d/1H2cBc8K6l7H9iZ70LDcCJkRojqNQWXzc/view?usp=share_link
https://drive.google.com/file/d/1E1V4yfeqq_G3Pqw2z_jBeRl0zTQ3aOCe/view?usp=share_link
Works fine, but i adjusted the texts that were out of layout and updated the file
new data.json: https://drive.google.com/file/d/1PWMIqHFT2ilJSFrIpnbhZnKBipGTDl4l/view?usp=share_link

Tk´s

**Comment by RonaldoRisso** [comment]
waiting for a 1.7 or 16.5 version... :)

**Comment by RonaldoRisso** [comment]
version 1.6.1 works perfectly, the portuguese translation It is ok
Tk´s again !!!

https://drive.google.com/file/d/1Ay8GJiSa9tUNc6AGXSTAphbQRaGz7nch/view?usp=share_link

**Comment by xreef** [comment]
Thanks to you for the support.
Bye Renzo

**Comment by RonaldoRisso** [comment]
Latest with camera
https://drive.google.com/file/d/1zJO1m-iflEajpjJwEHToxWcRZJ5y8qT4/view?usp=share_link

**Comment by xreef** [comment]
uuuu... thanks for sharing.. probably i add the image to the site.
Bye Renzo
