### ISSUE TITLE
Поворот камеры на 90 градусов

### ISSUE THREAD

**Issue by Sowa252** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#3]
Можно ли это как то сделать?

**Comment by xreef** [comment]
Hi Sowa252,
yes probably I insert that develop in the next release.

but please add your request to the specified forum.

https://www.mischianti.org/forums/forum/mischiantis-projects/mks-wifi-firmware-and-beeprint-web-interface/

Bye Renzo

**Comment by xreef** [comment]
Duplicate https://www.mischianti.org/forums/topic/beeprint-enhancement-camera-rotation/
