### ISSUE TITLE
Fileerror on install Original firmware

### ISSUE THREAD

**Issue by ricardojlrufino** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#32]
I got File error on install   
https://github.com/xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface/tree/master/original  
 https://github.com/xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface/tree/master/original_14
 
 This, works
https://github.com/makerbase-mks/MKS-WIFI/blob/master/firmware_release/MksWifi_CS1.0.4_200227.zip

**Comment by xreef** [comment]
Hi,
It's very strange, try to install via SD card.
Bye Renzo

**Comment by FedorSosnin** [comment]
I too get a file error. Reads "{"err": "404: / NOT FOUND”}” when going to the web interface. Tried the SD method several times. The way I got it to work was I had to restore back to the original firmware THEN install the wifi bin and THEN install the WEB bin via SD card. Got it running now. Thanks, this is beautiful!
