### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by Stewie-040882** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#33]
need to update from and to
char* firmwareVersion = "MISCHIANTI_v1.3"
const char* firmwareVersion = "MISCHIANTI_v1.3";

need to update to have a return value
int package_static_ip_info()
int package_net_para()

im new to coding but assuming its "return 0" at the end

**Comment by xreef** [comment]
Thanks,
yes probably yes, but that are the original function from mks release, I'm going to check.
Bye Renzo

**Comment by Stewie-040882** [comment]
im doing my best to learn, compile, and flash so that i can try to assist you. but ive tested around 4 compiles today but broke wifi connection each time, soim doing something wrong lol

**Comment by xreef** [comment]
WIFImanager hasn't the management of the dns, so it can't work with the standard version.
Here the fixed version.
https://github.com/xreef/WiFiManager
Bye Renzo

**Comment by Stewie-040882** [comment]
That's not the problem, I use "mks.bin" and connect to WiFi, I then upload "beeprint Web.bin", then upload "beeprint wifi.bin" everything working great.
  I compile new "beeprint wifi.bin" from code using arduino IDE, and wifi is broken "wifi starting up" message on printer.  Flash "beeprint wifi.bin" everything's great again. 
   I need to learn coding and compiling. Your code is great 👍

**Comment by xreef** [comment]
Hi Stewie,
did you check this article?
https://mischianti.org/2021/11/21/mks-wifi-for-makerbase-robin-pcb-and-how-to-compile-upload-firmware-2/
Here I added all steps to do the correct compilation (with the library I used).
Bye Renzo
