### ISSUE TITLE
Can't upload MksWifi_WebView.bin

### ISSUE THREAD

**Issue by lufton** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#38]
I'm not quite understand if I'm doing everything right.
I have Flyingbear Ghost 5 with Marlin firmware. Trying to upload `MksWifi_WebView.bin` from web interface, it waits around 30 seconds and then I receive "Connection was reset" message from browser. So it looks like it wasn't applied. Then I tried to flash `MksWifi.bin` and it was successful, but then I don't have root page /. It displays 404 error. So I have uploaded original wifi firmware and still can't upload `MksWifi_WebView.bin`.

**Comment by xreef** [comment]
Hi lufton,
Probably the wifi signal is bad, try to use the SD as explained in the article to upload the firmware.
Bye Renzo
