### ISSUE TITLE
Flash Feature

### ISSUE THREAD

**Issue by Stewie-040882** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#39]
Hi Mischanti, i dont know if youre aware, but the example config for AI Thinker flash has been changed to a slider, could you change your code to be a slider too? or provide a link to a cam config with a button? Thanks

I love the work youve done already, and constantly tell the Fokoos members to use your code. Thanks

**Comment by xreef** [comment]
Hi Stewie,
Thanks for the support.

It can be a beautiful features, but I create the firmware for the esp32 cam to support the button and multiple wifi.
https://github.com/xreef/esp32-cam_camera_webserver_enhanced

I add this to the possible enhancement.
Bye Renzo
