### ISSUE TITLE
"Drag to move" do not work in Safari or Chrome on macOS

### ISSUE THREAD

**Issue by alf45tar** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#4]
The interface is amazing. Never see anything like that on a ESP8266 board.
I am reporting a small bug with the + icon in the bottom. "Drag to move" do not work in Safari or Chrome on macOS.

**Comment by xreef** [comment]
Thanks, alf45tar,
I try to steal the iMac to my wife to do some debug.
Bye Renzo

**Comment by alf45tar** [comment]
Latest version fixed it.
Thanks

**Comment by xreef** [comment]
Thanks for your feedback.
Bye Renzo
