### ISSUE TITLE
Add mDNS responder

### ISSUE THREAD

**Issue by alf45tar** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#5]
The WiFi printer screen does not display the Printer Number as in the original firmware. Not a bug because it is not used anywhere.

May I suggest to implement the [mDNS responder](https://github.com/esp8266/Arduino/blob/4c07113ff55ad70f12e1401b64400ed36d353e1d/libraries/ESP8266mDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino#L53) in order to use the name instead of the IP that can change due to DHCP? 

Thanks
alf45tar

**Comment by xreef** [comment]
Thanks alf,
It's a good idea, I think I also add a screen to configure a static Ip.
Bye Renzo

**Comment by xreef** [comment]
Added!
