### ISSUE TITLE
Web error

### ISSUE THREAD

**Issue by WonderCRM** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#6]
Hello, several errors appear in the web application.

Uncaught TypeError: t.refreshChart is not a function
```
Lb(Mb(t = a.call(this, e)), "refreshData", (function() {
   t.refreshChart()  *
}
```

warning: logic (L(CRON_START)-2) is still running after 60s, forget to call done()? For non-ending logic, set warnTimeout: 0
```
pi((function() {
   console.error("warning: logic (".concat(r, ") is still running after ").concat(o / 1e3, "s, forget to call done()? For non-ending logic, set warnTimeout: 0"))
}
```

**Comment by xreef** [comment]
Hi WonderCMR,
I know of that, It's don't cause any problem, but I'm going to remove it on the next release.
Thanks Renzo
