### ISSUE TITLE
Head fan

### ISSUE THREAD

**Issue by WonderCRM** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#8]
The work of the cooling fan of the part is not displayed correctly. He works, in the web app displayed 0.

**Comment by xreef** [comment]
Fan information is not available from MCU firmware.
Bye Renzo

**Comment by WonderCRM** [comment]
It turns out that you can only set the value, but not know the real?

**Comment by xreef** [comment]
Yes, the communication protocol from MKS WiFi and MCU is limited, and for the fan, I only send a GCode command with only ok as a result.
Bye Renzo
