### ISSUE TITLE
Drag&drop file on upload widget

### ISSUE THREAD

**Issue by alf45tar** [xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface#9]
Thanks for version 1.4.
I am reporting a minor bug also present in previous one.
Using file drag&drop with upload widget do not enable "Upload" and "Upload and Print" buttons.

**Comment by xreef** [comment]
Hi @alf45tar,
drag and drop on upload file is not enabled, probably an artifact on Mac.
Bye Renzo
